language: ruby
rvm:
- 2.3.5
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: MPtkYReFPK2DHik1vYfzGXgEmhxyudl/nbc4XaUkfRdJV7N73naIGLEuOTwzLCx1ZHszCChOrr02CCpjELiKQnVry6VaDppSiEHLHlKJGL6SZwsQ+kdXNdsB2gJWmliM7WE32Kzp2rYlAJfwcixHExSXh5Obbo8u42E5D47GRI7i4GiSj920qxNnZmz3yu4T8R7rrzup4H9wXGQ8BYKad+hgzvHZGyuBXDYA5AEwOHPR1jiRcfgLITkDVo+CMBElE7EGt2kuGHvTetpz4z0iz1RaVp8zsfVQ1O7ziArD/ktUfpYbZUCP57U5xDy/BzoOsPpkozaoYPcwGCvt3v07BxwRlDfvEkiljsbSiP9HGXkVWw6z+p29vC1KGbCxZUOLtt6sRPD+gs7c/6Vk81HxyxVJjxntpGneNNVuowMtJynuSwFYyFDIVx7MC5wQ9XDEnEyaw+8O82EKeSuqdJ/7mla6YkoMwwza/EX9D7/mE9rUNRxdaAqTAaugVAzT+Rg0gTBAy/SqbM86kXijQ+gNnJW70LTiMKP0DZPWSeBT3i3cLz2dtAcjgRD2DamiX9BLc/WqKGRxLYI+/BS1Qygqvl4x8UGTBA5zCdEV8mzjoS2MBTo+yX2wwMMYbOz9Z76W83edz9CkpSK0V9DcETmpC1NJJ1/XSPbfb9Xx/aOOP1E=
